### ISSUE TITLE
Argument 'groups' has incorrect type (expected list, got map)

### ISSUE THREAD

**Issue by bratao** [timvieira/vocrf#1]
First of all, congratulations @timvieira  on the draft paper and the code release. This in invaluable for the NLP community.

While testing this code, I faced the following error:

```
>python vocrf/pos/tagfail.py --tag-type upos --lang English --C .01 --budget 1500 --inner-iterations 1 --outer-iterations 2 --initial-order 0 --max-order 0 --context-count 5 --dump /tmp/foo
context count filter threshold 5
allowed_contexts: 17
(sizes 1: 17)
Features (train) 100.0% (12543/12543) [===============================] 00:00:10
Features (dev) 100.0% (2002/2002) [===================================] 00:00:01
Traceback (most recent call last):
  File "vocrf/pos/tagfail.py", line 111, in <module>
    main()
  File "vocrf/pos/tagfail.py", line 39, in main
    _main(args)
  File "vocrf/pos/tagfail.py", line 105, in _main
    dump = args.dump)
  File "C:\Python36\lib\site-packages\vocrf-1.0-py3.6-win-amd64.egg\vocrf\activeset.py", line 60, in __init__
    self.dense = OnlineProx(self.group_structure(), self.H, L=L, C=self.regularizer)
TypeError: Argument 'groups' has incorrect type (expected list, got map)
```

activeset.py inherits model.pyx, and the function group_structure returns a map

```
    def group_structure(self):
        G = groups(self.C)
        return map(lambda g: list(sorted(map(self.context_feature_id, g))), G.values())
```

On the object OnlineProx in  Spom.pxy ,  the set_groups is decelerated to receive a list:
```
    def set_groups(self, list groups):
        self.G = len(groups)
        self.groups.clear()    # clear out old version!
```

Thank you!

**Comment by bratao** [comment]
Nevermind, this was a mistake during my Python 3 port. I will commit this port in a fork soon. Thank you!
